string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
string =  hello world
baudrate:115200 bits:8 parity:0 stop:0 ---check Successfully
Done.
